---
# tasks file for roles/master-healthcheck

#########################
# Test Master cluster health

- name: Grab Master Public URL
  shell: "grep ^masterPublicURL: /etc/origin/master/master-config.yaml | cut -f2 -d ' '"
  register: masterurl
- debug: var=masterurl.stdout_lines

- name: Check Master API/Controllers health
  uri:
    url: "{{ masterurl.stdout }}/healthz"
    return_content: yes
  register: healthz
- debug: var=healthz.content

- name: Fail if "OK" is not in the API output
  fail:
  when: "'ok' not in healthz.content"

##########################
# Test ETCD cluster health

- name: Grab ETCD local API
  shell: "grep ETCD_ADVERTISE_CLIENT_URLS= /etc/etcd/etcd.conf | cut -f2 -d="
  register: etcdapi
- debug: var=etcdapi.stdout_lines

- name: Check ETCD Cluster health
  shell: etcdctl --endpoints {{ etcdapi.stdout }} --ca-file=/etc/origin/master/master.etcd-ca.crt --cert-file=/etc/origin/master/master.etcd-client.crt --key-file=/etc/origin/master/master.etcd-client.key cluster-health
  register: health
- debug: var=health.stdout_lines

- name: Fail if "cluster is healthy" is not in the cluster-health output
  fail:
  when: "'cluster is healthy' not in health.stdout"


##########################
# Check ETCD member list

- name: Grab ETCD local API
  shell: "grep ETCD_ADVERTISE_CLIENT_URLS= /etc/etcd/etcd.conf | cut -f2 -d="
  register: etcdapi
- debug: var=etcdapi.stdout_lines

- name: Check ETCD Cluster health
  shell: etcdctl --endpoints {{ etcdapi.stdout }} --ca-file=/etc/origin/master/master.etcd-ca.crt --cert-file=/etc/origin/master/master.etcd-client.crt --key-file=/etc/origin/master/master.etcd-client.key member list
  register: health
- debug: var=health.stdout_lines

- name: Fail if "cluster is healthy" is not in the cluster-health output
  fail:
  when: "'isLeader' not in health.stdout"


