---
# tasks file for roles/node-healthcheck


##################
# Disk Space (Future implementation - ansibel_mount fact variable)

- name: Check /root disk space
  shell: "df -h /root | awk {'print $4'} | grep -v Avail | grep G | sed s/G//g"
  register: output
- debug: var=output.stdout_lines

- name: Fail if it has less than 2G available space
  fail:
  when: "output.stdout_lines < 2"


- name: Check /var/log disk space
  shell: "df -h /var/log | awk {'print $4'} | grep -v Avail | grep G | sed s/G//g"
  register: output
- debug: var=output.stdout_lines

- name: Fail if it has less than 2G available space
  fail:
  when: "output.stdout_lines < 2"

- name: Check Docker disk space
  shell: "docker info |grep -i 'Data Space Available:'"
  register: output
- debug: var=output.stdout_lines


###########################
# Docker Package version


- name: Check Docker version
  #shell: "docker version |grep -i '^ Version'"
  shell: "docker info | grep 'Server Version'"
  register: output
- debug: var=output.stdout_lines

- name: Fail if docker version mismatch	
  fail:
  when: "'1.12.6' not in output.stdout"


